<div class="content">
    <h1>Rotas</h1>

    <table>
        <tr>
            <th>N&uacute;mero</th>
            <th>Identifica&ccedil;&atilde;o</th>
            <th>Pontos</th>
        </tr>
        <?php foreach ($this->buses as $bus) : ?>
            <tr>
                <td><?php echo $bus->getIdBus(); ?></td>
                <td><?php echo $bus->getDescription(); ?></td>
                <td><?php
                    foreach ($bus->getPoints() as $point) :
                        echo $point->getLabel() . ' ';
                    endforeach;
                ?>
                </td>
            </tr>
            <?php endforeach; ?>
    </table>
</div>