<div class="content">
    <h1>Ônibus</h1>

    <ul>
        <?php foreach ($this->routes as $route) : ?>
            <li><?php echo $route->getIdBus() . ' - ' .$route->getDescription(); ?></li>
        <?php endforeach; ?>
    </ul>


    <?php
    $form = $this->form;

    $form->setAttribute('action', $this->url('routes', array('controller' => 'buses', 'action' => 'insert')));

    $form->prepare();
    echo $this->form()->openTag($form);

    echo $this->formRow($form->get('idbus'));
    echo $this->formRow($form->get('description'));
    echo $this->formRow($form->get('qnt_points')) . '<br />';
    echo $this->formSubmit($form->get('submit'));

    echo $this->form()->closeTag();
    ?>
</div>